server:
  port: 0

spring:
  application:
    name: review-service
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 500
        format_sql: true
        show_sql: true
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true

springdoc:
  packagesToScan: com.curady.reviewservice

---

spring:
  config:
    activate:
      on-profile: local
  application:
    name: review-service
  datasource:
    url: jdbc:mariadb://localhost:3306/curady_review
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mariadb://curady-review-db.cd3lqz4oykix.ap-northeast-2.rds.amazonaws.com:3306/curady_review
    driver-class-name: org.mariadb.jdbc.Driver
    username: roman
    password: ro-man-0509

eureka:
  client:
    service-url:
      defaultZone: http://10.0.140.187:8761/eureka
